name: vente
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.0
  cloud_firestore: ^0.12.9+5
  provider: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/c1.jpg
    - images/m1.jpg
    - images/m2.jpg
    - images/w1.jpg
    - images/w3.jpg
    - images/w4.jpg
    - images/cats/tshirt.png
    - images/cats/accessories.png
    - images/cats/dress.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/jeans.png
    - images/cats/shoe.png
    - images/products/blazer1.jpeg
    - images/products/dress1.jpeg
    - images/products/LGOLED.jpeg
    - images/products/PC.jpeg
    - images/products/switch.jpeg
    - images/products/switchlite.jpeg
    - images/products/ps4.jpeg
    - images/products/xbox.jpeg
    - images/products/iphone.jpeg
    - images/products/corsair.jpeg
    - images/products/razer.jpeg
    - images/products/asus.jpeg
    - images/products/asusVG.jpeg
    - images/products/mac.jpeg
    - images/products/imac.jpeg
    - images/products/beko.jpeg
    - images/products/vaiselle.jpeg
    - images/products/whirlpool.jpeg
    - images/products/bosh.jpeg
    - images/products/frigo.jpeg
    - images/products/hotte.jpeg
    - images/products/dyson.jpeg
    - images/products/xiaomi.jpeg
    - images/products/robot.jpeg
    - images/products/bebe.jpeg
    - images/products/calor.jpeg
    - images/products/chaise.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
